imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    translator: ~
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Social\SiteBundle\Entity\User

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 268931159818428 
    secret: 6d165f2df2bbac0924dd5e8032867d61 
    cookie: true
    permissions: [email, user_birthday, user_location]

fos_twitter:
    file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key: MRAXhACUuskeJs8E8FqJiA 
    consumer_secret: TkpEIc6BwV7C9CND6vo2fPt67rC9QI6gCfud9FlaeI 
    callback_url: http://www.symfony2social.com/twitter/login_check

services:
    my.facebook.user:
        class: Social\SiteBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
  
    my.twitter.user:
        class: Social\SiteBundle\Security\User\Provider\TwitterProvider
        arguments:
            twitter: "@fos_twitter.service"
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"        

#    ajax_success_handler:
#         class: Social\SiteBundle\Security\Authentication\AjaxSuccessHandler
#         arguments:   
#            response: 
 

    sonata.social.admin.config:
          class: Social\SiteBundle\Admin\ConfigAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: social_config, label: config }
          arguments: [null, Social\SiteBundle\Entity\Config, SocialSiteBundle:ConfigAdmin]

