
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#

index_slug:
    pattern: /{slug}
    defaults: { _controller: AppAdminBundle:Content:slug }

index:
    pattern: /
    defaults: { _controller: AppAdminBundle:Content:slug }

AppSecurityBundle:
    resource: "@AppSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout

_fb_security_check:
    pattern:  /facebook/login_check

_twitter_security_check:
    pattern:  /twitter/login_check

_twitter_oauth:
    pattern:  /twitter/oauth

_admin_login:
    pattern:  /admin/login
    defaults: { _controller: AppAdminBundle:Security:login }

_admin_check:
    pattern:  /admin/login_check
    defaults: { _controller: AppAdminBundle:Security:login_check }

_admin_logout:
    pattern:  /admin/logout
    defaults: { _controller: AppAdminBundle:Security:logout }

admin_index:
    pattern:  /admin/dashboard
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

AppAdminBundle:
    resource: "@AppAdminBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
