security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                damonp: { password: f627555b50c305f5050915e1ac411b9569469ff3, roles: [ 'ROLE_SUPER_ADMIN' ] }
                admin: { password: b614dc1ce8413ff6cf4db192c5b62e6a86090846, roles: [ 'ROLE_SUPER_ADMIN' ] }
                # admin / passw0rd22

        chain_provider:
            providers: [fos_userbundle, my_fos_facebook_provider, my_fos_twitter_provider]

        fos_userbundle:
            id: fos_user.user_manager

        my_fos_facebook_provider:
            id: my.facebook.user

        my_fos_twitter_provider:
            id: my.twitter.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern:  ^/admin/login$
            security: false

        admin:
            pattern:    ^/admin/
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/dashboard
                use_referer: false
            logout:
                path:   /admin/logout
                target: /

        main:
            pattern: .*
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                post_only: false
            logout:       true
            anonymous:    true

        public:
            pattern:  /
            fos_facebook:
                login_path: /facebook/login
                check_path: /facebook/login_check
                default_target_path: /
                provider: my_fos_facebook_provider
            fos_twitter:
                login_path: /twitter/login
                check_path: /twitter/login_check
                default_target_path: /
                provider: my_fos_twitter_provider

            anonymous: ~
            logout:
                handlers: ["fos_facebook.logout_handler"]
                delete_cookies: [oauth_token]


    access_control:
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

